#### 인덱싱

In [ ]:
list1 = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(list1[0][0][0])
print(list1[0][1][1])
print(list1[1][1][0])

1
4
7


In [ ]:
arr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1[0][0][0])
print(arr1[0][1][1])
print(arr1[1][1][0])

1
4
7


In [ ]:
arr1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1[0,0,0])
print(arr1[0,1,1])
print(arr1[1,1,0])

1
4
7


In [ ]:
arr1 = np.array(
                [[1,2],
                 [3,4],
                 [5,6]])
# 0행 가져와 2차원 배열 만들기
print(arr1[[0]])
# 0, 2행 가져와 2차원 배열 만들기
print(arr1[[0,2]])
# 1,4,5 가지고오기
print(arr1[[0,1,2],[0,1,0]])
# 같은 위치 데이터 여러번 사용가능
print(arr1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [ ]:
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

# 다음 코드의 실행결과는?
print(arr2[b,c])

[ 1  6  7 11]


### Boolean 인덱싱

In [2]:
import numpy as np

In [25]:
arr1 = np.array([1,2,3,4,5])

print(arr1[[True,False,True,True,False]])
print(arr1[arr1 > 3])

[1 3 4]
[4 5]


In [24]:
score = np.array([[78, 91, 84, 89, 93, 65],
                  [82, 87, 96, 79, 91, 73]])
print(score[0][(score[0] >= 90)])
print(score[1][(score[1] >= 90)])

[91 93]
[96 91]
