#### Arange (Array + Range)

In [4]:
import numpy as np

In [9]:
print(np.array(range(31)))

print(np.arange(31))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [19]:
print(np.arange(1,21,2))
print(np.arange(1,2,0.2))
print(np.arange(10,0,-2))

[ 1  3  5  7  9 11 13 15 17 19]
[1.  1.2 1.4 1.6 1.8]
[10  8  6  4  2]


#### Arange + Reshape

In [21]:
print(np.arange(1,26).reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [46]:
# 100 - 190 10간격 2, 5 행렬
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [52]:
print(np.arange(-2,2.1,0.5).reshape(1,3,3))

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


#### Zeros - 0으로 채워진 배열 생성

In [75]:
print(np.zeros(5,np.int8))
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]
[0 0 0 0 0]


In [62]:
print(np.zeros((2,3)))
print(np.zeros((2,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


#### Ones - 1로 채워진 배열 생성

In [81]:
print(np.ones((5,5),np.int8))
print(np.ones((5,5),np.int8).dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int8


#### Empty - 비어있는 배열 생성

In [85]:
print(np.empty((2,3),np.int8))

[[1 1 1]
 [1 1 1]]


#### Zeros_like, Ones_like, Empty_like - 기존의 배열을 0, 1 , empty로 변환

In [91]:
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [96]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [101]:
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#### Identity - 단위 행렬


In [123]:
print(np.identity((5),np.str_))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


In [122]:
print(np.identity((2),np.int8))

[[1 0]
 [0 1]]


#### Eye - 대각선이 1로 채워지는 행렬(위치 지정 가능)
np.eye(size,M,k,dtype)</br>
M = 보여지는 열의 갯수</br>
k = 대각선의 시작위치

In [134]:
print(np.eye((5),M=10 ,k=2),np.int8)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]] <class 'numpy.int8'>


In [150]:
print(np.eye((5),M=10 ,k=5, dtype= np.int8))

[[0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


#### Full - 입력 값으로 채워지는 행렬

In [155]:
print(np.full((2,5),'hi'))

[['hi' 'hi' 'hi' 'hi' 'hi']
 ['hi' 'hi' 'hi' 'hi' 'hi']]


In [159]:
print(np.ones((3,3), np.int8) * 3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


#### Random.ranint - 주어진 범위 안의 랜덤한 값 추출 함수

In [234]:
# 0-5 까지 정수중 무작위 뽑기
print(np.random.randint(6))
# 0- 20 까지 정수중 무작위 3개 뽑고 배열생성
print(np.random.randint(1,21,3))


3
[ 7 14 12]


#### Random.rand - 랜덤값으로 채워지는 배열

In [283]:
# 1차원 배열
print(np.random.rand(3)) 
print()
# 2차원 배열
print(np.random.rand(2,5)) 

[0.68270418 0.94931665 0.39364778]

[[0.70863301 0.51624043 0.09582645 0.98035002 0.04580512]
 [0.48677771 0.12371409 0.048529   0.6275689  0.96100858]]


#### Random.randn - 랜덤값으로 채워지는 배열(평균0, 표준편자1의 표준정규분포 난수)

In [284]:
print(np.random.randn(3))

[-0.8688912   0.24913853 -0.04640236]
