In [2]:
import numpy as np

#### 배열 수직 합치기(Vstack)

In [3]:
vector1 = [1,2,3]
vector2 = [4,5,6]
print(np.vstack([vector1, vector2]))

[[1 2 3]
 [4 5 6]]


#### 배열 수평 합치기(Hstack)

In [4]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1, vector2]))

[[1 4]
 [2 5]
 [3 6]]


#### 배열 합치기 (Concatenate)

In [5]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.concatenate([vector1, vector2],axis=0))

[1 2 3 4 5 6]


In [6]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print('수직 합치기\n',np.concatenate([vector1, vector2],axis=0))
print()
print('수평 합치기\n',np.concatenate([vector1, vector2],axis=1))

수직 합치기
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

수평 합치기
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
# 2차원 + 1차원
matrix = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([matrix, vector],axis=1))

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [8]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print('수직 합치기\n', np.concatenate([matrix1,matrix2],axis=0))
print()
print('수평 합치기\n', np.concatenate([matrix1,matrix2],axis=1))

수직 합치기
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

수평 합치기
 [[1 2 5 6]
 [3 4 7 8]]


####  Transpose - 행, 열 위치변경

In [10]:
matrix3 = np.array([[5,6]])
print(matrix3.transpose())
print(matrix3.T)
print(matrix3.shape, matrix3.transpose().shape)


[[5]
 [6]]
[[5]
 [6]]
(1, 2) (2, 1)


#### Transpose + Concatenate

In [15]:
print(np.concatenate([matrix1, matrix3]))
# print(np.concatenate([matrix1, matrix3],axis=1))
print()
print(np.concatenate([matrix1, matrix3.T],axis=1))


[[1 2]
 [3 4]
 [5 6]]

[[1 2 5]
 [3 4 6]]
