In [1]:
import numpy as np

In [2]:
a = np.array(1)
a

array(1)

In [3]:
ndarr_1 = np.array([1, 2, 3])
print(ndarr_1)

[1 2 3]


In [4]:
ndarr_2 = np.array([1, 2.0, 3])
print(ndarr_2)

[1. 2. 3.]


In [5]:
ndarr_3 = np.array([1, 2.0, '3'])
print(ndarr_3)

['1' '2.0' '3']


#### 배열의 정보 확인
#### 자료형 확인 속성
- ndarray.dtpye

In [6]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)


int32
float64
<U32


In [7]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

dtype2 = np.array([1,2,3], dtype=np.float64)
print(dtype2.dtype) 

dtype2 = np.array([1,2,3], dtype=np.str0)
print(dtype2.dtype)

int8
float64
<U1


In [8]:
dtype4 = np.array([1,2.1,'3'], dtype=np.int32)
print(dtype4.dtype)
#dtype5 = np.array([1,'data',print], dtype=np.float)
#print(dtype5.dtype)

int32


In [9]:
vecter = np.array([1,2,3])

print(vecter)       # 값
print(vecter.shape) # 크기
print(vecter.ndim)  # 차원
print(vecter.dtype) # 타입

[1 2 3]
(3,)
1
int32


In [10]:
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)       # 값
print(matrix.shape) # 크기
print(matrix.ndim)  # 차원
print(matrix.dtype) # 타입

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [11]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(tensor)       # 값
print(tensor.shape) # 크기
print(tensor.ndim)  # 차원
print(tensor.dtype) # 타입

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
3
int32


In [12]:
matrix = np.array([[1,2,3],[2,4,6],[3,6,9]])

print(matrix)       # 값
print(matrix.shape) # 크기
print(matrix.ndim)  # 차원
print(matrix.dtype) # 타입

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
2
int32


In [22]:
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1, type(arr1))

arr2 = [4,5,6]
list2 = list(arr2)
print(list2, type(list2))

[1 2 3] <class 'numpy.ndarray'>
[4, 5, 6] <class 'list'>


In [23]:
list3 = [[1,2,3],[4,5,6]]
arry3 = np.array(list3)
print(list3)

list4 = [[1,2,3,4],[5,6,7]]
arry4 - np.arrayb

[[1, 2, 3], [4, 5, 6]]


In [26]:
tuple1 = (1,2,3)
arr1 = np.array(tuple1)
print(arr)

arr2 = ([4,5,6])
tuple2 = tuple(arr2)
print(tuple2)

[1 2 3]
(4, 5, 6)


In [29]:
set1 ={1,2,3}
arr1 = np.array(set1)
print(arr1)

print(arr1.size)

{1, 2, 3}
1


In [30]:
dict1 ={'a':1, 'b':2, 'c':3}
arr1 = np.array(dict1)
print(arr1)

{'a': 1, 'b': 2, 'c': 3}
