In [1]:
import numpy as np

In [3]:
a = np.array(1)
a

array(1)

In [4]:
ndarr_1 = np.array([1, 2, 3])
print(ndarr_1)

[1 2 3]


In [6]:
ndarr_2 = np.array([1, 2.0, 3])
print(ndarr_2)

[1. 2. 3.]


In [7]:
ndarr_3 = np.array([1, 2.0, '3'])
print(ndarr_3)

['1' '2.0' '3']


#### 배열의 정보 확인
#### 자료형 확인 속성
- ndarray.dtpye

In [18]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)


int32
float64
<U32


In [23]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

dtype2 = np.array([1,2,3], dtype=np.float64)
print(dtype2.dtype) 

dtype2 = np.array([1,2,3], dtype=np.str0)
print(dtype2.dtype)

int8
float64
<U1


In [24]:
dtype4 = np.array([1,2.1,'3'], dtype=np.int32)
print(dtype4.dtype)
#dtype5 = np.array([1,'data',print], dtype=np.float)
#print(dtype5.dtype)

int32


In [27]:
vecter = np.array([1,2,3])

print(vecter)       # 값
print(vecter.shape) # 크기
print(vecter.ndim)  # 차원
print(vecter.dtype) # 타입

[1 2 3]
(3,)
1
int32


In [29]:
matrix = np.array([[1,2,3],[4,5,6]])

print(matrix)       # 값
print(matrix.shape) # 크기
print(matrix.ndim)  # 차원
print(matrix.dtype) # 타입

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [30]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

print(tensor)       # 값
print(tensor.shape) # 크기
print(tensor.ndim)  # 차원
print(tensor.dtype) # 타입

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
3
int32
