#### 슬라이싱

In [2]:
import numpy as np

In [4]:
matirx = np.array([[1,2,3,4,5],
                  [6,7,8,9,10],
                  [11,12,13,14,15],
                  [16,17,18,19,20]])

In [9]:
# 0열 전체 슬라이싱print(matirx[:,0])

[ 1  6 11 16]


In [22]:
# 0열 전체 슬라이싱 (2차원 유지)
print(matirx[:,[0]])
print(matirx[:,:1])

[[ 1]
 [ 6]
 [11]
 [16]]
[[ 1]
 [ 6]
 [11]
 [16]]


In [17]:
# 1행 전체 슬라이싱
print(matirx[1,:])
print(matirx[1])


[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [20]:
# 1행 전체 슬라이싱(2차원 유지)
print(matirx[[1]])
print(matirx[1:2,:])


[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [24]:
# 3,4열 전체 슬라이싱
print(matirx[:,3:])


[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [30]:
# 0행 1-3열 슬라이싱
print(matirx[0,1:4])
print(matirx[0,1:-1])


[2 3 4]
[2 3 4]


In [31]:
# 2-3행, 2-4열 슬라이싱
print(matirx[2:4,2:])


[[13 14 15]
 [18 19 20]]


In [32]:
# 1-2행, 1-2열 슬라이싱
print(matirx[1:3,1:3])


[[ 7  8]
 [12 13]]


#### 인덱싱 + 슬라이싱

In [33]:
# 1,3행, 2-4열 슬라이싱
print(matirx[[1,3],2:])


[[ 8  9 10]
 [18 19 20]]


In [35]:
# 1-2행, 1,3열 슬라이싱
print(matirx[1:3,[1,3]])


[[ 7  9]
 [12 14]]


In [41]:
tensor = np.array([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                     [10,11,12]]])
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [82]:
# 10, 2, 6 배열 추출
print(tensor[[1,0,0],[1,0,1],[0,1,2]])
            #  차원     행      열

[10  2  6]


In [84]:
# [[1,2,   , [9,12] 추출
#   4,5]]
print(tensor[0,:2,:-1])
print(tensor[1,:,2])

[[1 2]
 [4 5]]
[ 9 12]
