#### Reshape(배열형태 변환)

In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]]) # 2x3 행렬
print(arr)
print(arr.reshape(3,2)) # reshape로 3x2 변환

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
print(arr.reshape(3,1,2)) # 3x1x2 배열로 변경

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [20]:
# ?x2 행 갯수 자동 변경
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [22]:
# 3x? 열 갯수 자동 변경
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [23]:
print(arr.reshape(6)) # 차원 줄이기

[1 2 3 4 5 6]


In [28]:
tensor = np.array(range(1,37))
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [29]:
# 3,3,4 형태로 reshape
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [34]:
# 9열인 2차원 배열 변형
print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]
