In [2]:
import numpy as np

#### 합(sum)

In [36]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix)
print()
print('배열의 합\n', matrix.sum())


[[1 2 3]
 [4 5 6]]

배열의 합
 21


In [34]:
print('행의 합\n', matrix.sum(axis=0)) # 행 끼리 더하기(세로)
print()
print('열의 합\n', matrix.sum(axis=1)) # 열 끼리 더하기(가로)

행의 합
 [5 7 9]

열의 합
 [ 6 15]


In [27]:
# 3차원 배열의 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print()
print('배열의 합\n', tensor.sum()) # np.sum(tensor)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

배열의 합
 171


In [25]:
print('차원의 합\n', tensor.sum(axis=0)) # 차원 끼리의 합
print()
print('행의 합\n', tensor.sum(axis=1)) # 행 끼리의 합
print()
print('열의 합\n', tensor.sum(axis=2)) # 열 끼리의 합


차원의 합
 [[21 24 27]
 [30 33 36]]

행의 합
 [[ 5  7  9]
 [17 19 21]
 [29 31 33]]

열의 합
 [[ 6 15]
 [24 33]
 [42 51]]


#### 평균(mean)

In [33]:
print(matrix)
print()
print('배열의 평균\n', matrix.mean()) # matrix의 평균
print()
print('행의 평균\n', matrix.mean(axis=0)) # 행의 평균
print()
print('열의 평균\n', matrix.mean(axis=1)) # 열의 평균


[[1 2 3]
 [4 5 6]]

배열의 평균
 3.5

행의 평균
 [2.5 3.5 4.5]

열의 평균
 [2. 5.]


#### 표준편차(std)

In [31]:
print('배열의 표준편차\n', matrix.std())
print()
print('행의 표준편차\n', matrix.std(axis=0))
print()
print('열의 표준편차\n', matrix.std(axis=1))

배열의 표준편차
 1.707825127659933

행의 표준편차
 [1.5 1.5 1.5]

열의 표준편차
 [0.81649658 0.81649658]


#### 그 외 수학 연산자

In [40]:
print('지수\n', np.exp(matrix))
print()
print('로그\n', np.log(matrix))
print()
print('제곱근\n', np.sqrt(matrix))
print()
print('삼각함수\n', np.sin(matrix))


지수
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

로그
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]

제곱근
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

삼각함수
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
