In [1]:
import numpy as np

#### 배열정렬(Sort)

In [11]:
vector = np.array([np.random.randint(1,100)
                   for n in range(5)])
print(vector)
print('오름차순 정렬\n',np.sort(vector)) # 오름차순 정렬
print('내림차순 정렬\n',np.sort(vector)[::-1]) # 내림차순 정렬

[38 19 37 88 50]
오름차순 정렬
 [19 37 38 50 88]
내림차순 정렬
 [88 50 38 37 19]


In [29]:
# for문 복습
# 리스트 a에 1~5 넣기
a = []
for i in range(1,6):
    a.append(i)
print(a)

# 다른방법
[i for i in range(1,6)]

# 활용
list1 = list(range(1,11))
list2 = [num * 3 for num in list1 if num % 2 == 1]
list2

[1, 2, 3, 4, 5]


[3, 9, 15, 21, 27]

In [39]:
matrix = np.array([np.random.randint(1,100)
                   for n in range(20)]).reshape(4,5)
print(matrix)
print()
print('열 기준 오름차순 정렬\n',np.sort(matrix)) # 열 기준 오름차순 정렬
print('행 기준 오름차순 정렬\n',np.sort(matrix,axis=0)) # 행 기준 오름차순 정렬
print()
print('열 기준 내림차순 정렬\n',np.sort(matrix)[::-1]) # 열 기준내림차순 정렬
print('행 기준 내림차순 정렬\n',np.sort(matrix,axis=0)[::-1]) # 행 기준 내림차순 정렬

[[89 43 39 72 21]
 [10 82  2 99 99]
 [98 60 15 61 66]
 [30 12 90 85 94]]

열 기준 오름차순 정렬
 [[21 39 43 72 89]
 [ 2 10 82 99 99]
 [15 60 61 66 98]
 [12 30 85 90 94]]
행 기준 오름차순 정렬
 [[10 12  2 61 21]
 [30 43 15 72 66]
 [89 60 39 85 94]
 [98 82 90 99 99]]

열 기준 내림차순 정렬
 [[12 30 85 90 94]
 [15 60 61 66 98]
 [ 2 10 82 99 99]
 [21 39 43 72 89]]
행 기준 내림차순 정렬
 [[98 82 90 99 99]
 [89 60 39 85 94]
 [30 43 15 72 66]
 [10 12  2 61 21]]
