In [1]:
import numpy as np

#### Index 값 추출

In [5]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
print(np.argmax(a),np.argmin(a))

9 0


In [9]:
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

[1 1 1 1 1]
[4 4]


In [20]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)
print()
print('수직 최대값 인덱스\n', np.argmax(b, axis=0))
print()
print('수평 최대값 인덱스\n', np.argmax(b, axis=1))


[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]

수직 최대값 인덱스
 [2 2 1 0]

수평 최대값 인덱스
 [3 2 1]


In [ ]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]


In [ ]:
print(a[b])

[4 5 6 7]


In [ ]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
9


In [ ]:
print(a[b])

19
