In [2]:
import numpy as np

#### 배열 연산

In [3]:
list1 = [1,2,3]
list2 = [4,5,6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)

[5 7 9]


In [5]:
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.int32).reshape(2,3)
print('더하기\n',arr1 + arr2)
print()
print('빼기\n',arr2 - arr1)
print()
print('곱하기\n',arr1 * arr2)
print()
print('나누기\n',arr2 / arr1)
print()
print('몫\n',arr2 // arr1)
print()
print('나머지\n',arr2 % arr1)
print()
print('제곱근\n',arr1 ** arr2)

더하기
 [[12. 14. 16.]
 [18. 20. 22.]]

빼기
 [[10. 10. 10.]
 [10. 10. 10.]]

곱하기
 [[11. 24. 39.]
 [56. 75. 96.]]

나누기
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]

몫
 [[11.  6.  4.]
 [ 3.  3.  2.]]

나머지
 [[0. 0. 1.]
 [2. 0. 4.]]

제곱근
 [[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]


#### 연산함수

In [6]:
print('더하기\n', np.add(arr1,arr2))
print()
print('빼기\n', np.subtract(arr2,arr1))
print()
print('곱하기\n', np.multiply(arr1,arr2))
print()
print('나누기\n', np.divide(arr2,arr1))

더하기
 [[12. 14. 16.]
 [18. 20. 22.]]

빼기
 [[10. 10. 10.]
 [10. 10. 10.]]

곱하기
 [[11. 24. 39.]
 [56. 75. 96.]]

나누기
 [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]


#### Brodcasting - 배열 모양이 다른경우 연산

In [7]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3 + arr4)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [ ]:
scalar = 10
vertor = np.array([1,2,3])
print(scalar + vertor)

[11 12 13]


In [ ]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)

[[11 12 13]
 [14 15 16]]


In [ ]:
scalar = 10
tensor = np.arange(1,19).reshape(3,2,3)
print(scalar + tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


In [ ]:
matrix = np.arange(1,10).reshape(3,3)
vertor = np.arange(11,14).reshape(1,3)
print(matrix)
print('    +    ')
print(vertor)
print()
print(matrix + vertor)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
    +    
[[11 12 13]]

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [ ]:
matrix = np.arange(1,10).reshape(3,3)
vertor = np.arange(11,14).reshape(3,1)
print(matrix)
print('    +    ')
print(vertor)
print()
print(matrix + vertor)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
    +    
[[11]
 [12]
 [13]]

[[12 13 14]
 [16 17 18]
 [20 21 22]]


In [ ]:
arr1 = np.array([1,2,3]).reshape(1,3)
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print()
print(arr2)
print()
print(arr1 + arr2)


[[1 2 3]]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1 * arr2)
print(np.dot(arr1,arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

[1 4 9]
14
14
14


In [17]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(arr3)
print(arr4)
print(np.dot(arr3,arr4))

[[1 2 3]
 [4 5 6]]
[[11 12]
 [13 14]
 [15 16]]
[[ 82  88]
 [199 214]]
