In [1]:
import numpy as np

#### 파일 입출력

In [5]:
n = np.random.randn(3,5)
print(n)
n.tofile('C:/STUDY/StudyPython/04.numpy/file/n.npy')

[[ 0.70396975  0.58308879 -1.16107468 -1.09363928  0.27499765]
 [ 0.90470207 -0.01679377  0.94446354 -0.09912007  0.02291036]
 [ 1.52559177  0.35213229  0.35259221  1.14007051  1.00487808]]


In [8]:
m = np.fromfile('./file/n.npy').reshape(3,5)
print(m)

[[ 0.70396975  0.58308879 -1.16107468 -1.09363928  0.27499765]
 [ 0.90470207 -0.01679377  0.94446354 -0.09912007  0.02291036]
 [ 1.52559177  0.35213229  0.35259221  1.14007051  1.00487808]]


In [12]:
# save, load - 파일 저장/불러오기
np.save('./file/n1.npy',n)
m1 = np.load('./file/n1.npy')
print(m1)

[[ 0.70396975  0.58308879 -1.16107468 -1.09363928  0.27499765]
 [ 0.90470207 -0.01679377  0.94446354 -0.09912007  0.02291036]
 [ 1.52559177  0.35213229  0.35259221  1.14007051  1.00487808]]
