In [2]:
import numpy as np

#### 파일 입출력

In [3]:
n = np.random.randn(3,5)
print(n)
n.tofile('C:/STUDY/StudyPython/04.numpy/file/n.npy')

[[ 0.63880227  1.16824118 -0.08993662 -1.42962114 -0.47811754]
 [-1.00933586 -1.32617984  2.35382711 -0.04131934 -1.00125026]
 [-0.56280116 -0.26220182 -0.35313379  0.07216263  0.12454392]]


In [5]:
m = np.fromfile('./file/n.npy').reshape(3,5)
print(m)

[[ 0.63880227  1.16824118 -0.08993662 -1.42962114 -0.47811754]
 [-1.00933586 -1.32617984  2.35382711 -0.04131934 -1.00125026]
 [-0.56280116 -0.26220182 -0.35313379  0.07216263  0.12454392]]


In [12]:
# save, load - 파일 저장/불러오기
np.save('./file/n1.npy',n)
m1 = np.load('./file/n1.npy')
print(m1)

[[ 0.70396975  0.58308879 -1.16107468 -1.09363928  0.27499765]
 [ 0.90470207 -0.01679377  0.94446354 -0.09912007  0.02291036]
 [ 1.52559177  0.35213229  0.35259221  1.14007051  1.00487808]]


In [8]:
np.savetxt('./file/n.txt',n)
m2 = np.loadtxt('./file/n.txt')
print(m2)

[[ 0.63880227  1.16824118 -0.08993662 -1.42962114 -0.47811754]
 [-1.00933586 -1.32617984  2.35382711 -0.04131934 -1.00125026]
 [-0.56280116 -0.26220182 -0.35313379  0.07216263  0.12454392]]


In [13]:
np.savetxt('./file/n.csv',n, delimiter=',')
m3 = np.loadtxt('./file/n.csv', delimiter=',')
print(m3)

[[ 0.63880227  1.16824118 -0.08993662 -1.42962114 -0.47811754]
 [-1.00933586 -1.32617984  2.35382711 -0.04131934 -1.00125026]
 [-0.56280116 -0.26220182 -0.35313379  0.07216263  0.12454392]]


In [35]:
a = np.arange(1,26,dtype=np.int8).reshape(5,5)

np.savetxt('./file/data.csv',a,delimiter=',')
np.savetxt('./file/data1.csv',np.arange(1,26,dtype=np.int8).reshape(5,5),delimiter=',')
arr = np.loadtxt('./file/data1.csv',delimiter=',',dtype=np.int8)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
arr1 = np.loadtxt('./data/06_data1.txt',delimiter='\t',dtype=np.str_)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [22]:
arr2 = np.loadtxt('./data/06_data2.txt',delimiter=',',dtype=int)
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


In [92]:
el = np.loadtxt('./data/ex1_지역별전기요금.csv',delimiter=',',dtype=int)
#print(el)
# 강원1	 경기2	경남3	경북4	광주5	대구6	대전7	부산8	서울9
# 세종10 울산11 인천12  전남13	전북14	제주15	충남16	충북17	

print(el[:5,:]) # 상위 5개 데이터 출력
print(el.shape)
print(np.unique(el[:,0]))

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]
(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [133]:
# 1열 기준 오름차순 정렬
print('1열 오름차순 인덱싱]\n', el[:,1].argsort())
print()
print('팬시인덱싱\n', el[el[:,1].argsort()])
print()
# 3열 기준 내림차순정렬
print('3열 내림차순 인덱싱]\n', el[:,3].argsort())
print()
print('팬시인덱싱\n', el[el[:,3].argsort()[::-1]])


1열 오름차순 인덱싱]
 [ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]

팬시인덱싱
 [[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]

3열 내림차순 인덱싱]
 [14  3 12 16  0 15 13  2  6  5 10  7  8  4 11  1  9]

팬시인덱싱
 [[     10   49394     580   57091]
 [      2 2827233     444   45111]
 [     12  734723     398   40049]
 [      5  380425     391   38020]
 [      9 2737725     361   36569]
 [      8  947300     366   36274]
 [     11  323151     353   35470]
 [      

In [142]:
# 총 가구수
print('가구수 합 1 =',np.sum(el[:,1]))
print('가구수 합 2 =',el[:,1].sum())
# 가구당 평균전력 사용량의 전국 평균값
print('전력 평균값 1 =', round(np.mean(el[:,2]),2))
print('전력 평균값 2 =',round(el[:,2].mean(),2))

가구수 합 1 = 14882047
가구수 합 2 = 14882047
전력 평균값 1 = 335.18
전력 평균값 2 = 335.18


In [151]:
# 무식하게 평균 구하기
el_sum = np.sum(el[:,2])
print('전력 총 합 =', el_sum)
n_rows = el.shape[0]
print('총 지역수 =', n_rows)
print('평균 = ', round(el_sum/n_rows,2))

전력 총 합 = 5698
총 지역수 = 17
평균 =  335.18


In [189]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과, 대상 가구수 추출
el_avr = round(el[:,2].mean(),2)
print(el[el[:,2]> el_avr,0:2])
a = el[el[:,2]> el_avr,0:2]
print()
# 가구당 평균 전력 사용량이 평균 이상인 지역과, 대상 가구수가 낮은 순서대로 추출
print(a[np.argsort(a[:,1])])
print(a[a[:,1].argsort()])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]

[[     10   49394]
 [     11  323151]
 [      5  380425]
 [      7  425659]
 [      6  668623]
 [     12  734723]
 [      8  947300]
 [      9 2737725]
 [      2 2827233]]
[[     10   49394]
 [     11  323151]
 [      5  380425]
 [      7  425659]
 [      6  668623]
 [     12  734723]
 [      8  947300]
 [      9 2737725]
 [      2 2827233]]


In [184]:
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',',dtype=int)
print(data)

# 발생년도 구분 발생건수 구성비(%) 증감수 증감률
		
# 강원1	 경기2	경남3	경북4	광주5	대구6	대전7	부산8	서울9
# 세종10 울산11	인천12	전남13	전북14	제주15	충남16	충북17	


[[2014    1  218    4   -9   -4]
 [2014    2  872   19  -45   -4]
 [2014    3  401    8  -45  -10]
 [2014    4  464   10  -41   -8]
 [2014    5   99    2   -5   -4]
 [2014    6  182    4   19   11]
 [2014    7   99    2    8    8]
 [2014    8  163    3  -47  -22]
 [2014    9  386    8   14    3]
 [2014   10   20    0    0    0]
 [2014   11  103    2  -16  -13]
 [2014   12  144    3   -6   -4]
 [2014   13  400    8  -35   -8]
 [2014   14  317    6  -35   -9]
 [2014   15   86    1  -14  -14]
 [2014   16  387    8   -5   -1]
 [2014   17  242    5  -31  -11]]


In [198]:
# 위 파일을 읽어보고 상위 3개의
data1 = data[data[:,2].argsort()]
print(data1[3])

[2014    7   99    2    8    8]
