In [13]:
import numpy as np
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',',dtype=int)

# 발생년도 구분 발생건수 구성비(%) 증감수 증감률
		
# 강원1	 경기2	경남3	경북4	광주5	대구6	대전7	부산8	서울9
# 세종10 울산11	인천12	전남13	전북14	제주15	충남16	충북17

print(data)

[[2014    1  218    4   -9   -4]
 [2014    2  872   19  -45   -4]
 [2014    3  401    8  -45  -10]
 [2014    4  464   10  -41   -8]
 [2014    5   99    2   -5   -4]
 [2014    6  182    4   19   11]
 [2014    7   99    2    8    8]
 [2014    8  163    3  -47  -22]
 [2014    9  386    8   14    3]
 [2014   10   20    0    0    0]
 [2014   11  103    2  -16  -13]
 [2014   12  144    3   -6   -4]
 [2014   13  400    8  -35   -8]
 [2014   14  317    6  -35   -9]
 [2014   15   86    1  -14  -14]
 [2014   16  387    8   -5   -1]
 [2014   17  242    5  -31  -11]]


#### [문제1] 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [63]:

print(data[:3,[0,2,3]])
#data[data[:,2].argsort()]

[[2014  218    4]
 [2014  872   19]
 [2014  401    8]]


#### [문제2] 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [36]:
print(data[data[:,1] == 8])

[[2014    8  163    3  -47  -22]]


#### [문제3] 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [88]:
print('합계 =', data[:,2].sum())
print('평균 =', round(data[:,2].mean(),2))

합계 = 4583
평균 = 269.59


#### [문제4] 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [94]:
a = data[data[:,4].argsort()]
print(a[0])

[2014    8  163    3  -47  -22]


#### [문제5] 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [96]:
print(data[data[:,5] == 0])

[[2014   10   20    0    0    0]]


#### [문제6] 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [97]:
print(data[data[:,2] >= 400][:,[1,2,4,5]])

[[  2 872 -45  -4]
 [  3 401 -45 -10]
 [  4 464 -41  -8]
 [ 13 400 -35  -8]]
